# Generated by Django 4.2.2 on 2023-06-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawDates',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='TotoResults',
            fields=[
                ('toto_draw_id', models.IntegerField(primary_key=True, serialize=False)),
                ('has_1', models.IntegerField(default=0)),
                ('has_2', models.IntegerField(default=0)),
                ('has_3', models.IntegerField(default=0)),
                ('has_4', models.IntegerField(default=0)),
                ('has_5', models.IntegerField(default=0)),
                ('has_6', models.IntegerField(default=0)),
                ('has_7', models.IntegerField(default=0)),
                ('has_8', models.IntegerField(default=0)),
                ('has_9', models.IntegerField(default=0)),
                ('has_10', models.IntegerField(default=0)),
                ('has_11', models.IntegerField(default=0)),
                ('has_12', models.IntegerField(default=0)),
                ('has_13', models.IntegerField(default=0)),
                ('has_14', models.IntegerField(default=0)),
                ('has_15', models.IntegerField(default=0)),
                ('has_16', models.IntegerField(default=0)),
                ('has_17', models.IntegerField(default=0)),
                ('has_18', models.IntegerField(default=0)),
                ('has_19', models.IntegerField(default=0)),
                ('has_20', models.IntegerField(default=0)),
                ('has_21', models.IntegerField(default=0)),
                ('has_22', models.IntegerField(default=0)),
                ('has_23', models.IntegerField(default=0)),
                ('has_24', models.IntegerField(default=0)),
                ('has_25', models.IntegerField(default=0)),
                ('has_26', models.IntegerField(default=0)),
                ('has_27', models.IntegerField(default=0)),
                ('has_28', models.IntegerField(default=0)),
                ('has_29', models.IntegerField(default=0)),
                ('has_30', models.IntegerField(default=0)),
                ('has_31', models.IntegerField(default=0)),
                ('has_32', models.IntegerField(default=0)),
                ('has_33', models.IntegerField(default=0)),
                ('has_34', models.IntegerField(default=0)),
                ('has_35', models.IntegerField(default=0)),
                ('has_36', models.IntegerField(default=0)),
                ('has_37', models.IntegerField(default=0)),
                ('has_38', models.IntegerField(default=0)),
                ('has_39', models.IntegerField(default=0)),
                ('has_40', models.IntegerField(default=0)),
                ('has_41', models.IntegerField(default=0)),
                ('has_42', models.IntegerField(default=0)),
                ('has_43', models.IntegerField(default=0)),
                ('has_44', models.IntegerField(default=0)),
                ('has_45', models.IntegerField(default=0)),
                ('has_46', models.IntegerField(default=0)),
                ('has_47', models.IntegerField(default=0)),
                ('has_48', models.IntegerField(default=0)),
                ('has_49', models.IntegerField(default=0)),
                ('additional_number', models.IntegerField()),
            ],
            options={
                'ordering': ('toto_draw_id',),
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('wind_direction', models.CharField(max_length=5)),
                ('wind_speed_min', models.FloatField()),
                ('wind_speed_max', models.FloatField()),
                ('humidity_min', models.FloatField()),
                ('humidity_max', models.FloatField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='totolyzer.drawdates')),
            ],
        ),
        migrations.AddField(
            model_name='drawdates',
            name='toto_draw_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='totolyzer.totoresults'),
        ),
    ]
