version: '3'

services:
  django_app:
    volumes:
      - static_vol:/app/staticfiles
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - django_app
volumes:
  static_vol: